version: "3.8"
services:
  kbf-frontend:
    image: nginx:1.25-alpine
    container_name: kbf-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
      - "443:443"
    volumes:
      - ../../frontend:/usr/share/nginx/html:ro
      - ./kbf.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
